version: "3"

services:

  libraries:
    volumes:
      # dist folder of each dependency to sync to other containers
      &distributable-shared
      - ./libs/example/dist:/home/node/project/libs/example/dist
      - ./libs/plugins/dist:/home/node/project/libs/plugins/dist
      - ./libs/prim/dist:/home/node/project/libs/prim/dist
      - ./ui/docs/dist:/home/node/project/ui/docs/dist

  backend:
    volumes: *distributable-shared

  frontend:
    volumes: *distributable-shared
