version: "3"

services:

  libraries:
    volumes:
      # dist folder of each dependency to sync to other containers
      &dist-shared
      - dist-example:/home/node/project/libs/example/dist
      - dist-plugins:/home/node/project/libs/plugins/dist
      - dist-prim:/home/node/project/libs/prim/dist
      - dist-docs:/home/node/project/libs/docs/dist

  backend:
    volumes: *dist-shared

  frontend:
    volumes: *dist-shared

volumes:
  dist-example:
  dist-plugins:
  dist-prim:
  dist-docs:
