version: "3"

# NOTE: this file is used in production for logging and metrics
# exposed ports should be blocked by firewall but allowed on internal network

services:

  # Metrics from Docker (fluentd) will be forwarded to fluentbit
  fluentbit:
    image: fluent/fluent-bit:1.8
    restart: "always"
    command: "/fluent-bit/bin/fluent-bit -c /configs/config.conf"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # NOTE: path base is given by primary Compose file (project directory)
      - ./misc/fluentbit.conf:/configs/config.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      HOST: $COMPOSE_HOST
      METRICS_COLLECTION_HOST: $METRICS_COLLECTION_HOST

  # Metrics to be pulled by Prometheus
  nodeexporter:
    image: prom/node-exporter:v1.3.1
    restart: "always"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
