version: 3

env:
  COMPOSE_FILE: "{{.COMPOSE_FILE}}"

tasks:

  ps:
    desc: "[{{.CHOSEN_ENV}}] List all running service names"
    cmds:
      - "docker compose ps --services"

  logs:
    desc: "[{{.CHOSEN_ENV}}] Show and follow recent logs for running services"
    cmds:
      - cmd: "docker compose logs -f --tail=25"
        ignore_error: true

  # NOTE: used in "common" Taskfile
  # LINK ./Taskfile.common.yml
  up-base:
    cmds:
      - cmd: "docker compose up -d"
      - task: logs

  down:
    desc: "[{{.CHOSEN_ENV}}] Stop all running services"
    cmds:
      - "docker compose down"
