// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PaperTest: typeof import('./src/components/PaperTest.vue')['default']
    PtsTest: typeof import('./src/components/PtsTest.vue')['default']
  }
}

export { }
