useTabs: true
printWidth: 120
semi: false
singleQuote: false
jsxSingleQuote: false
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: true
arrowParens: avoid
proseWrap: always

plugins:
  - "prettier-plugin-astro"
overrides:
  - files: "*.astro"
    options:
      parser: "astro"
