version: "3"

services:
  caddy:
    volumes:
      - ./proxy/prod.Caddyfile:/etc/caddy/Caddyfile:ro
    restart: "always"

  postgres:
    restart: "always"

  backend:
    # runtime: runsc
    build:
      context: ./apps/backend
      target: prod
    environment:
      - NODE_ENV=production
    restart: "always"

  frontend:
    # runtime: runsc
    build:
      context: ./apps/frontend
      target: prod
    environment:
      - NODE_ENV=production
    restart: "always"
