version: '3'

services:
  caddy:
    build:
      context: ./proxy
      target: prod
    restart: "always"

  postgres:
    restart: "always"

  backend:
    restart: "always"

  frontend:
    restart: "always"
