version: "3"

services:
  caddy:
    build:
      context: ./proxy
      target: prod
    restart: "always"

  postgres:
    restart: "always"

  backend:
    build:
      context: ./apps/backend
      target: prod
    environment:
      - NODE_ENV=production
    restart: "always"

  frontend:
    build:
      context: ./apps/frontend
      target: prod
    environment:
      - NODE_ENV=production
    restart: "always"
