version: "3"

services:
  caddy:
    volumes:
      - ./proxy/prod.Caddyfile:/etc/caddy/Caddyfile:ro
    restart: "always"

  postgres:
    restart: "always"

  # NOTE: using staging for now since website hasn't been officially published yet

  backend:
    image: doseofted/prim-backend:staging
    # runtime: runsc
    environment:
      - NODE_ENV=production
    restart: "always"

  frontend:
    image: doseofted/prim-frontend:staging
    # runtime: runsc
    environment:
      - NODE_ENV=production
    restart: "always"

  # NOTE if postgres database is used in future, this needs to be removed for migration sake
  # watchtower:
  #   image: containrrr/watchtower:1.5.3
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
