version: "3"

services:
  # reverse proxy for all other services
  caddy:
    environment:
      - WEBSITE_HOST
      - ADMIN_EMAIL
    volumes:
      - ./data/caddy/config:/config
      - ./data/caddy/data:/data
    ports:
      - "80:80"
      - "443:443"
    restart: "no"

  # database available for use in project
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_DB="prim"
      - POSTGRES_USER="proper"
      - POSTGRES_PASSWORD
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: "no"
