version: "3"

services:
  caddy:
    restart: "always"

  postgres:
    restart: "always"

  backend:
    runtime: runsc
    environment:
      - NODE_ENV=production
    restart: "always"

  frontend:
    runtime: runsc
    environment:
      - NODE_ENV=production
    restart: "always"

  # NOTE if postgres database is used in future, this needs to be removed for migration sake
  # watchtower:
  #   image: containrrr/watchtower:1.5.3
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
