version: "3"

services:
  # reverse proxy for all other services
  caddy:
    image: caddy:2.6.4
    environment:
      - WEBSITE_HOST
      - ADMIN_EMAIL
      - PRERELEASE_PASSWORD
    volumes:
      - ./data/caddy/config:/config
      - ./data/caddy/data:/data
      - ./proxy/base.Caddyfile:/etc/caddy/base.Caddyfile:ro
    user: 1000:1000
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    restart: "no"
    networks:
      - internal

  # database available for use in project
  postgres:
    image: postgres:15.2
    environment: &database-creds
      POSTGRES_DB: "prim"
      POSTGRES_USER: "proper"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: "no"
    networks:
      - database

  # backend that will serve the API
  backend:
    image: doseofted/prim-backend:latest
    environment:
      <<: *database-creds
      WEBSITE_HOST: $WEBSITE_HOST
      CONTAINED: "true"
    restart: "no"
    networks:
      - database
      - internal

  # frontend used to serve UI that communicates with API
  frontend:
    image: doseofted/prim-frontend:latest
    environment:
      NEXT_PUBLIC_WEBSITE_HOST: $WEBSITE_HOST
      NEXT_PUBLIC_CONTAINED: "true"
    restart: "no"
    networks:
      - internal

networks:
  internal:
  database:
