version: "3"

services:
  # reverse proxy for all other services
  caddy:
    image: doseofted/prim-proxy:latest
    environment:
      - WEBSITE_HOST
      - ADMIN_EMAIL
    volumes:
      - ./data/caddy/config:/config
      - ./data/caddy/data:/data
    ports:
      - "80:80"
      - "443:443"
    restart: "no"
    networks:
      - internal

  # database available for use in project
  postgres:
    image: postgres:15.1
    environment: &database-creds
      POSTGRES_DB: "prim"
      POSTGRES_USER: "proper"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: "no"
    networks:
      - database

  # backend that will serve the API
  backend:
    image: doseofted/prim-backend:latest
    environment:
      <<: *database-creds
      WEBSITE_HOST: $WEBSITE_HOST
      CONTAINED: "true"
    restart: "no"
    networks:
      - database
      - internal

  # frontend used to serve UI that communicates with API
  frontend:
    image: doseofted/prim-frontend:latest
    environment:
      NEXT_PUBLIC_WEBSITE_HOST: $WEBSITE_HOST
      NEXT_PUBLIC_CONTAINED: "true"
    restart: "no"
    networks:
      - internal

networks:
  internal:
  database:
