version: "3"
services:

  proxy:
    restart: "no"
    volumes:
      - ./project/proxy/dev.Caddyfile:/etc/caddy/Caddyfile

  api:
    build:
      args:
        NODE_ENV: "development"
    restart: "no"
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "development"
    volumes:
      - ./project/api/src:/home/node/src
      - ./project/api/package.json:/home/node/package.json
      - ./project/api/yarn.lock:/home/node/yarn.lock

  ui:
    build:
      args:
        NODE_ENV: "development"
    restart: "no"
    ports:
      - "3000:3000"
    command: "dev --host=0.0.0.0 --port=3000"
    environment:
      NODE_ENV: "development"
    volumes:
      - ./project/ui/public:/home/node/public
      - ./project/ui/src:/home/node/src
      - ./project/ui/index.html:/home/node/index.html
      - ./project/ui/vite.config.ts:/home/node/vite.config.ts
      - ./project/ui/package.json:/home/node/package.json
      - ./project/ui/yarn.lock:/home/node/yarn.lock

  db:
    restart: "no"
    ports: 
      - "27017:27017"
