version: "3"
services:

  api:
    build:
      context: ./project
    container_name: api

  db:
    image: mongo:4.4-bionic
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - ./data/mongo:/data/db
