version: "3"
services:

  server:
    image: caddy:2.4.3-alpine
    container_name: server
    environment:
      HOST: $HOST
    volumes:
      - ./data/server/config:/config
      - ./data/server/data:/data
    ports:
      - "80:80"
      - "443:443"

  api:
    build:
      context: ./api
    container_name: api

  db:
    image: mongo:4.4-bionic
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - ./data/db:/data/db
