version: "3"

services:

  caddy:
    logging:
      &logging
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
    restart: "always"
    volumes:
      - ./project/server/prod.Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/server:/srv:ro

  postgres:
    logging: *logging
    restart: "always"

  backend:
    logging: *logging
    restart: "always"
    build:
      args:
        NODE_ENV: "production"
    environment:
      NODE_ENV: "production"

  frontend:
    logging: *logging
    restart: "always"
    build:
      args:
        NODE_ENV: "production"
    environment:
      NODE_ENV: "production"

  libraries:
    logging: *logging
    restart: "always"
    build:
      args:
        NODE_ENV: "production"
    environment:
      NODE_ENV: "production"
