version: "3"

x-logging:
  &logging
  driver: "fluentd"
  options:
    fluentd-address: "localhost:24224"
    fluentd-async: "true"

services:

  caddy:
    logging:
      <<: *logging
    restart: "always"
    volumes:
      - ./project/server/prod.Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/server:/srv:ro

  postgres:
    logging:
      <<: *logging
    restart: "always"

  backend:
    logging:
      <<: *logging
    restart: "always"
    build:
      args:
        NODE_ENV: "production"
    environment:
      NODE_ENV: "production"

  # frontend:
  #   logging:
  #     <<: *logging
  #   restart: "always"
  #   build:
  #     args:
  #       NODE_ENV: "production"
  #   environment:
  #     NODE_ENV: "production"
  #   command: "preview"
  #   volumes:
  #     - ./data/server:/home/node/project/dist

  libraries:
    logging:
      <<: *logging
    restart: "always"
    build:
      args:
        NODE_ENV: "production"
    environment:
      NODE_ENV: "production"
