version: "3"
services:

  proxy:
    restart: "always"
    volumes:
      - ./project/proxy/prod.Caddyfile:/etc/caddy/Caddyfile

  api:
    build:
      args:
        NODE_ENV: "production"
    restart: "always"
    environment:
      NODE_ENV: "production"

  ui:
    build:
      args:
        NODE_ENV: "production"
    restart: "always"
    command: "serve --host=0.0.0.0 --port=3000"
    environment:
      NODE_ENV: "production"

  db:
    restart: "always"

