version: "3"
services:

  proxy:
    image: caddy:2.4.3-alpine
    container_name: proxy
    environment:
      HOST: $HOST
    volumes:
      - ./project/proxy/base.Caddyfile:/etc/caddy/base.Caddyfile
      - ./data/server/config:/config
      - ./data/server/data:/data
    ports:
      - "80:80"
      - "443:443"

  api:
    build:
      context: ./project/api
    container_name: api

  ui:
    build:
      context: ./project/ui
    container_name: ui

  db:
    image: mongo:4.4-bionic
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - ./data/db:/data/db
