version: "3"
services:

  server:
    restart: "always"
    volumes:
      - ./project/proxy/prod.Caddyfile:/etc/caddy/Caddyfile

  api:
    build:
      args:
        NODE_ENV: "production"
    restart: "always"
    environment:
      NODE_ENV: "production"

  db:
    restart: "always"
