version: "3"

services:

  caddy:
    restart: "always"
    volumes:
      - ./project/server/prod.Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/server:/srv:ro

  postgres:
    restart: "always"

  libraries:
    image: scratch
    # image: "doseofted/${COMPOSE_PROJECT_NAME}-libraries:v0.0.1"
    restart: "always"

  backend:
    image: "doseofted/${COMPOSE_PROJECT_NAME}-backend:v0.0.1"
    restart: "always"

  frontend:
    image: "doseofted/${COMPOSE_PROJECT_NAME}-frontend:v0.0.1"
    restart: "always"
