version: "3"

services:

  caddy:
    logging:
      &logging
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
    restart: "always"
    volumes:
      - ./project/server/prod.Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/server:/srv:ro

  postgres:
    logging: *logging

  libraries:
    logging: *logging
    image: scratch
    # image: "doseofted/${COMPOSE_PROJECT_NAME}-libraries:v0.0.1"

  backend:
    logging: *logging
    image: "doseofted/${COMPOSE_PROJECT_NAME}-backend:v0.0.1"

  frontend:
    logging: *logging
    image: "doseofted/${COMPOSE_PROJECT_NAME}-frontend:v0.0.1"
