version: "3"
services:

  proxy:
    image: caddy:2.4.3-alpine
    container_name: ${PROJECT_NAME}_proxy
    environment:
      HOST: $HOST
    volumes:
      - ./project/proxy/base.Caddyfile:/etc/caddy/base.Caddyfile
      - ./data/server/config:/config
      - ./data/server/data:/data
    ports:
      - "80:80"
      - "443:443"

  api:
    build:
      context: ./project/api
    container_name: ${PROJECT_NAME}_api
    environment:
      DATABASE_USERNAME: $DB_USER
      DATABASE_PASSWORD: $DB_PASS

  ui:
    build:
      context: ./project/ui
    stop_signal: SIGKILL # no state attached, just kill it
    container_name: ${PROJECT_NAME}_ui

  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./data/db:/var/lib/postgresql/data
