packages:
  - libs/*
  - apps/*

catalog:
  '@types/node': ^25.5.0
  '@typescript/native-preview': 7.0.0-dev.20260315.1
  tsdown: ^0.21.3

engineStrict: true

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@go-task/cli'
  - esbuild

sideEffectsCache: false

supportedArchitectures:
  cpu: [ current ]
  os: [ current ]
