packages:
  - libs/*
  - apps/*

auditConfig: {}

catalog:
  '@types/node': ^24.2.0
  '@typescript/native-preview': 7.0.0-dev.20250807.1
  tsdown: ^0.13.3

engineStrict: true

onlyBuiltDependencies:
  - '@go-task/cli'
  - esbuild

sideEffectsCache: false

supportedArchitectures:
  cpu: [current]
  os: [current]
