packages:
  - libs/*
  - apps/*

auditConfig: {}

catalog:
  '@types/node': ^24.5.2
  '@typescript/native-preview': 7.0.0-dev.20250922.1
  tsdown: ^0.14.2

engineStrict: true

onlyBuiltDependencies:
  - '@go-task/cli'
  - esbuild

sideEffectsCache: false

supportedArchitectures:
  cpu: [current]
  os: [current]
