# https://taskfile.dev
version: 3

includes:
  # Project-wide includes
  dev: ./misc/Taskfile.dev.yml
  docker: ./misc/Taskfile.docker.yml
  # Sub-project-specific includes
  backend:
    taskfile: ./apps/backend/Taskfile.yml
    dir: ./apps/backend
    optional: true
  frontend:
    taskfile: ./apps/frontend/Taskfile.yml
    dir: ./apps/frontend
    optional: true
  frontend2:
    taskfile: ./apps/frontend-2/Taskfile.yml
    dir: ./apps/frontend-2
    optional: true

tasks:

  default:
    cmds:
      - "task --list"
