version: 3

tasks:
  # Run dependencies as cmds so they run sequentially (it's slower this way but otherwise output is unreadable)
  build-dependencies:
    cmds:
      - task: :docker:base:build
      - tasK: :docker:prod:build

  build:
    desc: "Build frontend image for production use"
    deps:
      - build-dependencies
    cmds:
      - "docker build -t doseofted/prim-frontend ."

  prod:
    desc: "Run frontend image in production mode"
    deps:
      - build
    cmds:
      - "docker run -it --rm doseofted/prim-frontend {{.CLI_ARGS}}"

  dev:
    desc: "Build and run frontend image targeting \"dev\" stage with src folder mounted to host"
    deps:
      - build-dependencies
    cmds:
      - "docker build -t doseofted/prim-frontend-dev --target=dev ."
      - |
        docker run -it --rm \
          -v "$(pwd)/src:/home/node/project/apps/frontend/src" \
          -p 3000:3000 \
          doseofted/prim-frontend-dev {{.CLI_ARGS}}
