version: 3

tasks:

  build:
    desc: "Build frontend image for production use"
    deps:
      - :docker:build-base-images
    cmds:
      - "docker build -t doseofted/prim-frontend ."

  prod:
    desc: "Run frontend image in production mode"
    deps:
      - build
    cmds:
      - "docker run -it --rm -p 3000:3000 doseofted/prim-frontend {{.CLI_ARGS}}"

  dev:
    desc: "Build and run frontend image targeting \"dev\" stage with src folder mounted to host"
    deps:
      - :docker:build-base-images
    cmds:
      - "docker build -t doseofted/prim-frontend-dev --target=dev ."
      - |
        docker run -it --rm \
          -v "$(pwd)/src:/home/node/project/apps/frontend/src" \
          -p 3000:3000 -p 24678:24678 \
          doseofted/prim-frontend-dev {{.CLI_ARGS}}

  entrypoint:
    desc: "Run frontend's entrypoint for full development setup"
    env:
      NODE_ENV: development
    cmds:
      - pnpm entrypoint
