version: 3

tasks:
  build:
    desc: "Build backend image for production use"
    deps:
      - :docker:build-base-images
    cmds:
      - "docker build -t doseofted/prim-backend ."

  prod:
    desc: "Run backend image in production mode"
    deps:
      - build
    cmds:
      - "docker run -it --rm doseofted/prim-backend {{.CLI_ARGS}}"

  dev:
    desc: 'Build and run backend image targeting "dev" stage with src folder mounted to host'
    deps:
      - :docker:build-base-images
    cmds:
      - "docker build -t doseofted/prim-backend-dev --target=dev ."
      - |
        docker run -it --rm \
          -v "$(pwd)/src:/home/node/project/apps/backend/src" \
          -p 3001:3001 \
          doseofted/prim-backend-dev {{.CLI_ARGS}}

  entrypoint:
    desc: "Run backend's entrypoint for full development setup"
    env:
      NODE_ENV: development
    cmds:
      - pnpm entrypoint
