version: "3"

services:
  libraries:
    # NOTE: specify image's name to be used as a referenced tag in other Dockerfiles
    # since the frontend and backend depend on this image. It has been excluded
    # from the base Compose configuration since Docker Compose will try to pull
    # if .image is present (even though I'm only using it as a tag name, not as a
    # reference to an external registry).
    image: libraries
