version: 3

tasks:
  run:
    vars:
      WORKING_DIR:
        sh: pwd
    cmds:
      - |
        docker run -it --rm \
          -p 80:80 -p 443:443 \
          -e WEBSITE_HOST -e ADMIN_EMAIL \
          -v {{.WORKING_DIR}}/base.Caddyfile:/etc/caddy/base.Caddyfile \
          -v {{.WORKING_DIR}}/{{.TARGET_CONFIG}}.Caddyfile:/etc/caddy/Caddyfile \
          caddy:2.6.2 {{.CLI_ARGS}}

  # FIXME: dev mode won't work until dev cert volumes (in parent folder) are mounted as volume
  dev:
    desc: "Run Caddy image in dev mode"
    cmds:
      - task: run
        vars: { TARGET_CONFIG: "{{.TASK}}" }

  prod:
    desc: "Run Caddy image in production mode"
    cmds:
      - task: run
        vars: { TARGET_CONFIG: "{{.TASK}}" }

  staging:
    desc: "Run Caddy image in staging mode"
    cmds:
      - task: run
        vars: { TARGET_CONFIG: "{{.TASK}}" }
