pipeline:
  apps:base:try:
    image: woodpeckerci/plugin-docker-buildx
    commands:
      - echo "Hello"

  apps:base:dev:
    image: &build-image woodpeckerci/plugin-docker-buildx
    group: base
    settings: &base-settings
      dry_run: true
      context: ./
      platforms: linux/amd64
      tag: ["latest"]
      repo: doseofted/monorepo-build
      output: type=oci,dest=doseofted--monorepo-build.tar
      dockerfile: ./Monorepo.base.Dockerfile
    when: &base-when
      event: [tag, push]
      tag: v*
      branch: release/*

  apps:base:prod:
    image: *build-image
    group: base
    settings:
      <<: *base-settings
      repo: doseofted/monorepo-production
      output: type=oci,dest=doseofted--monorepo-production.tar
      dockerfile: ./Monorepo.prod.Dockerfile
    when: *base-when

  frontend:build:production:
    image: *build-image
    commands:
      - docker load doseofted--monorepo-build.tar
      - docker load doseofted--monorepo-production.tar
    group: build
    secrets: &build-secrets
      - docker_username
      - docker_password
    settings: &frontend-settings
      repo: doseofted/prim-frontend
      dockerfile: ./apps/frontend/Dockerfile
      context: ./apps/frontend
      platforms: linux/amd64
      tag: ["${CI_COMMIT_TAG}", "latest"]
    when: &when-production
      event: [tag]
      tag: v*

  frontend:build:staging:
    image: *build-image
    group: build
    secrets: *build-secrets
    settings:
      <<: *frontend-settings
      tag: ["v${CI_COMMIT_BRANCH##release/}-staging", "staging"]
    when: &when-staging
      event: [push]
      branch: release/*

  backend:build:production:
    image: *build-image
    group: build
    secrets: *build-secrets
    settings: &backend-settings
      repo: doseofted/prim-backend
      dockerfile: ./apps/backend/Dockerfile
      context: ./apps/backend
      platforms: linux/amd64
      tag: ["${CI_COMMIT_TAG}", "latest"]
    when: *when-production

  backend:build:staging:
    image: *build-image
    group: build
    secrets: *build-secrets
    settings:
      <<: *backend-settings
      tag: ["v${CI_COMMIT_BRANCH##release/}-staging", "staging"]
    when: *when-staging
