pipeline:
  docs:base:dev:
    image: &base-image node:19.6-bullseye
    group: base
    commands:
      - npm install -g @go-task/cli
      - task docker:base:build
    when: &base-when
      event: [tag, push]
      tag: v*
      branch: release/*

  docs:base:prod:
    image: *base-image
    group: base
    commands:
      - npm install -g @go-task/cli
      - task docker:prod:build
    when: *base-when

  docs:build:production:
    image: &build-image woodpeckerci/plugin-docker-buildx
    group: build
    secrets: &build-secrets
      - docker_username
      - docker_password
    settings: &frontend-settings
      repo: doseofted/prim-frontend
      dockerfile: ./apps/frontend/Dockerfile
      context: ./apps/frontend
      platforms: linux/amd64
      tag: ["${CI_COMMIT_TAG}", "latest"]
    when: &when-production
      event: [tag]
      tag: v*

  # TODO: add backend/production build (or exclude from production launch)

  docs:build:staging:
    image: *build-image
    group: build
    secrets: *build-secrets
    settings:
      <<: *frontend-settings
      tag: ["v${CI_COMMIT_BRANCH##release/}-staging", "staging"]
    when: &when-staging
      event: [push]
      branch: release/*

  # TODO: add backend/staging build (or exclude from production launch)
