pipeline:
  npm:preview:
    image: node:19.4-bullseye
    environment:
      NODE_ENV: "production"
    commands:
      - corepack enable
      - pnpm install
      - pnpm task dev:build
      - pnpm task dev:test
    when:
      event: [push]
      branch:
        - release/*

  npm:official:
    image: node:19.4-bullseye
    secrets: [npm_username, npm_api_token]
    environment:
      NODE_ENV: "production"
    commands:
      - corepack enable
      - pnpm install
      - pnpm task dev:build
      - pnpm task dev:test
      - pnpm task changeset:publish
    when:
      event: [tag]
      tag: v*
