name: Build Prim+RPC Project
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     cache: "pnpm"
      - run: corepack enable
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm task dev:build
      - name: Test
        run: pnpm task dev:test
      # - name: Create Release PR
      #   uses: changesets/action@v1
      #   with:
      #     publish: pnpm task dev:changeset:publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
