name: Publish Prim+RPC

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    # NOTE: don't add any Turbo cache here, publishing workflow needs to be clean
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # NOTE: don't use cache for publishing (install needs to be clean)
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm turbo lint
      - name: Build
        run: pnpm turbo build
      - name: Test
        run: pnpm turbo test
      - name: Release
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}"
