name: Build Prim+RPC
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm task dev:build
      - name: Test
        run: pnpm task dev:test
      - name: Create Release PR
        uses: changesets/action@v1
        with:
          publish: pnpm task dev:changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
