name: Publish Prim+RPC

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: "pnpm"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm task dev:build
      - name: Test
        run: pnpm task dev:test
      - name: Release
        uses: changesets/action@v1
        with:
          publish: pnpm task dev:changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}"
